const Career = require('./models/Career');
const QuizQuestion = require('./models/Quiz');
const Course = require('./models/Course');
const College = require('./models/College');
const ChatRoom = require('./models/ChatRoom');

// ═══════════════════════════════════════════════════════════════
// 56 CAREERS — adapted from plan/seed.js
// ═══════════════════════════════════════════════════════════════

const careerData = [

    // ═══════════════════════════════════════════════
    // 💼 PRIVATE SECTOR  (15 careers)
    // ═══════════════════════════════════════════════
    {
        title: 'Software Developer / SDE',
        slug: 'software-developer',
        category: 'Private Sector',
        salaryRange: '₹4–12 LPA',
        demandLevel: 'Very High',
        description: 'Build and maintain software applications at product companies and service firms. Roles range from backend/frontend to full-stack across web, mobile, and enterprise systems.',
        icon: '💻',
        isTrending: true,
        skills: ['DSA', 'Java', 'Python', 'C++', 'System Design', 'Git'],
        branches: ['CSE', 'IT'],
    },
    {
        title: 'Full Stack Developer',
        slug: 'full-stack-developer',
        category: 'Private Sector',
        salaryRange: '₹5–14 LPA',
        demandLevel: 'Very High',
        description: 'Design and develop both client-side and server-side of web applications. Work with React/Next.js on the frontend and Node.js/Django/Spring on the backend.',
        icon: '🌐',
        isTrending: true,
        skills: ['React', 'Node.js', 'PostgreSQL', 'MongoDB', 'REST APIs', 'TypeScript'],
        branches: ['CSE', 'IT'],
    },
    {
        title: 'Data Scientist / Data Analyst',
        slug: 'data-scientist',
        category: 'Private Sector',
        salaryRange: '₹6–15 LPA',
        demandLevel: 'High',
        description: 'Extract insights from large datasets using statistical methods and ML models. Data Analysts focus on dashboards and reporting; Data Scientists build predictive models.',
        icon: '📊',
        isTrending: true,
        skills: ['Python', 'SQL', 'Machine Learning', 'Tableau', 'Statistics', 'Pandas'],
        branches: ['CSE', 'IT', 'ECE'],
    },
    {
        title: 'AI / ML Engineer',
        slug: 'ai-ml-engineer',
        category: 'Private Sector',
        salaryRange: '₹8–20 LPA',
        demandLevel: 'Very High',
        description: 'Design and deploy machine learning models and AI systems. Work on NLP, computer vision, recommendation systems, and generative AI products.',
        icon: '🤖',
        isTrending: true,
        skills: ['Python', 'TensorFlow', 'PyTorch', 'Deep Learning', 'Linear Algebra', 'MLOps'],
        branches: ['CSE', 'IT', 'ECE'],
    },
    {
        title: 'DevOps / Cloud Engineer',
        slug: 'devops-cloud-engineer',
        category: 'Private Sector',
        salaryRange: '₹6–16 LPA',
        demandLevel: 'High',
        description: 'Bridge development and operations by automating CI/CD pipelines, managing cloud infrastructure, and ensuring system reliability and scalability.',
        icon: '☁️',
        isTrending: true,
        skills: ['AWS', 'Docker', 'Kubernetes', 'Linux', 'Terraform', 'CI/CD'],
        branches: ['CSE', 'IT'],
    },
    {
        title: 'Cybersecurity Analyst',
        slug: 'cybersecurity-analyst',
        category: 'Private Sector',
        salaryRange: '₹5–14 LPA',
        demandLevel: 'High',
        description: 'Protect organizations from cyber threats through vulnerability assessment, penetration testing, and security monitoring. High demand due to rising cyberattacks.',
        icon: '🔐',
        isTrending: true,
        skills: ['Networking', 'Ethical Hacking', 'Python', 'Kali Linux', 'OWASP', 'SIEM tools'],
        branches: ['CSE', 'IT', 'ECE'],
    },
    {
        title: 'Embedded Systems Engineer',
        slug: 'embedded-systems-engineer',
        category: 'Private Sector',
        salaryRange: '₹4–10 LPA',
        demandLevel: 'Medium',
        description: 'Develop firmware and software for hardware devices like microcontrollers, IoT devices, automotive systems, and consumer electronics.',
        icon: '🔧',
        isTrending: false,
        skills: ['C', 'C++', 'RTOS', 'Microcontrollers', 'IoT', 'ARM Architecture'],
        branches: ['ECE', 'EEE', 'CSE'],
    },
    {
        title: 'Product Manager',
        slug: 'product-manager',
        category: 'Private Sector',
        salaryRange: '₹10–25 LPA',
        demandLevel: 'High',
        description: 'Own the product lifecycle from ideation to launch. Bridge engineering, design, and business teams. High-paying role suited for engineers with business acumen.',
        icon: '📋',
        isTrending: true,
        skills: ['Product Strategy', 'Agile', 'User Research', 'SQL', 'Communication', 'Roadmapping'],
        branches: ['CSE', 'IT', 'ECE', 'MECH'],
    },
    {
        title: 'QA / Test Engineer',
        slug: 'qa-test-engineer',
        category: 'Private Sector',
        salaryRange: '₹3–8 LPA',
        demandLevel: 'Medium',
        description: 'Ensure software quality through manual and automated testing. Write test scripts, identify bugs, and validate functionality before product releases.',
        icon: '✅',
        isTrending: false,
        skills: ['Selenium', 'Java', 'Manual Testing', 'JIRA', 'API Testing', 'Test Plans'],
        branches: ['CSE', 'IT'],
    },
    {
        title: 'UI / UX Designer',
        slug: 'ui-ux-designer',
        category: 'Private Sector',
        salaryRange: '₹4–12 LPA',
        demandLevel: 'Medium',
        description: 'Design user interfaces and experiences for web and mobile products. Combine design thinking with user research to build intuitive and beautiful products.',
        icon: '🎨',
        isTrending: false,
        skills: ['Figma', 'Adobe XD', 'Design Thinking', 'Wireframing', 'Prototyping', 'User Research'],
        branches: ['CSE', 'IT', 'ALL'],
    },
    {
        title: 'Business / Systems Analyst',
        slug: 'business-analyst',
        category: 'Private Sector',
        salaryRange: '₹5–12 LPA',
        demandLevel: 'Medium',
        description: 'Analyze business processes and translate them into technical requirements. Work between stakeholders and development teams in IT services and consulting firms.',
        icon: '📈',
        isTrending: false,
        skills: ['Excel', 'SQL', 'Communication', 'Requirements Gathering', 'JIRA', 'Power BI'],
        branches: ['CSE', 'IT', 'MECH', 'CIVIL'],
    },
    {
        title: 'VLSI / Chip Design Engineer',
        slug: 'vlsi-chip-design-engineer',
        category: 'Private Sector',
        salaryRange: '₹6–18 LPA',
        demandLevel: 'High',
        description: "Design integrated circuits and chips for semiconductors, CPUs, and SoCs. High demand due to India's semiconductor push with players like Intel, Qualcomm, and AMD hiring locally.",
        icon: '🔬',
        isTrending: true,
        skills: ['Verilog', 'VHDL', 'Cadence', 'Synopsys', 'Digital Electronics', 'FPGA'],
        branches: ['ECE', 'EEE'],
    },
    {
        title: 'Core Mechanical / Civil / EEE Engineer',
        slug: 'core-engineering',
        category: 'Private Sector',
        salaryRange: '₹3–8 LPA',
        demandLevel: 'Medium',
        description: 'Work in manufacturing, construction, power, and infrastructure industries. Roles include design, maintenance, project management in companies like L&T, Tata, BHEL (private arm).',
        icon: '⚙️',
        isTrending: false,
        skills: ['AutoCAD', 'SolidWorks', 'MATLAB', 'Project Management', 'Domain Knowledge'],
        branches: ['MECH', 'CIVIL', 'EEE'],
    },
    {
        title: 'Technical Consultant',
        slug: 'technical-consultant',
        category: 'Private Sector',
        salaryRange: '₹6–15 LPA',
        demandLevel: 'Medium',
        description: 'Advise organizations on technology adoption, digital transformation, and system integration. Hired by firms like TCS, Infosys, Accenture, Deloitte, and Wipro.',
        icon: '🤝',
        isTrending: false,
        skills: ['Communication', 'Domain Expertise', 'Problem Solving', 'ERP Tools', 'SAP', 'PowerPoint'],
        branches: ['CSE', 'IT', 'MECH', 'CIVIL', 'EEE'],
    },
    {
        title: 'Freelancer / Remote Developer',
        slug: 'freelancer-remote-developer',
        category: 'Private Sector',
        salaryRange: '₹3–30 LPA',
        demandLevel: 'High',
        description: 'Work independently for global clients on platforms like Upwork, Toptal, and Fiverr. Choose your tech stack, set your rates, and work from anywhere.',
        icon: '🧑‍💻',
        isTrending: true,
        skills: ['Any Tech Stack', 'Client Communication', 'Time Management', 'Portfolio Building'],
        branches: ['CSE', 'IT', 'ECE'],
    },

    // ═══════════════════════════════════════════════
    // 🏛️ GOVERNMENT  (15 careers)
    // ═══════════════════════════════════════════════
    {
        title: 'PSU Engineer (NTPC / ONGC / BHEL / IOCL / GAIL)',
        slug: 'psu-engineer',
        category: 'Government',
        salaryRange: '₹7–15 LPA',
        demandLevel: 'Very High',
        examRoute: 'GATE Score',
        description: 'Join India\'s top Public Sector Undertakings as an Engineer/Management Trainee. Permanent job with pension, housing, and excellent allowances alongside competitive salary.',
        icon: '🏭',
        isTrending: true,
        skills: ['GATE CSE/ECE/MECH/EEE', 'Core Engineering', 'Aptitude', 'GD/Interview'],
        branches: ['CSE', 'ECE', 'MECH', 'EEE', 'CIVIL'],
    },
    {
        title: 'ISRO Scientist / Engineer',
        slug: 'isro-scientist',
        category: 'Government',
        salaryRange: '₹8–14 LPA',
        demandLevel: 'High',
        examRoute: 'ISRO Centralised Recruitment Board (ICRB)',
        description: 'Work on India\'s space missions, satellite systems, and rocket technology at one of the world\'s top space agencies. Extremely prestigious and intellectually rewarding.',
        icon: '🚀',
        isTrending: true,
        skills: ['GATE', 'Programming', 'Embedded Systems', 'Math', 'Domain Engineering'],
        branches: ['CSE', 'ECE', 'MECH', 'EEE'],
    },
    {
        title: 'DRDO Scientist B',
        slug: 'drdo-scientist',
        category: 'Government',
        salaryRange: '₹90,000/month',
        demandLevel: 'High',
        examRoute: 'GATE / DRDO CEPTAM Direct Recruitment',
        description: 'Contribute to defence research at DRDO — developing AI systems, robotics, cybersecurity tools, and military-grade embedded systems for national security.',
        icon: '🛡️',
        isTrending: false,
        skills: ['GATE', 'AI/ML', 'Embedded C', 'Cybersecurity', 'Robotics'],
        branches: ['CSE', 'ECE', 'MECH', 'EEE'],
    },
    {
        title: 'IES / ESE Officer (Indian Engineering Services)',
        slug: 'ies-ese-officer',
        category: 'Government',
        salaryRange: '₹10–15 LPA',
        demandLevel: 'Medium',
        examRoute: 'UPSC Engineering Services Examination (ESE)',
        description: 'Class-I officer role managing government engineering projects in Railways, Telecom, Power, and Defence. Prestigious equivalent of IAS but for engineers.',
        icon: '🎖️',
        isTrending: false,
        skills: ['Core Engineering Subjects', 'General Studies', 'Interview Prep', 'ESE Syllabus'],
        branches: ['CSE', 'ECE', 'MECH', 'EEE', 'CIVIL'],
    },
    {
        title: 'IAS / IPS / IFS Officer',
        slug: 'ias-ips-ifs-officer',
        category: 'Government',
        salaryRange: '₹8–15 LPA + perks',
        demandLevel: 'High',
        examRoute: 'UPSC Civil Services Examination (CSE)',
        description: 'The most prestigious government career in India. Manage administration, law enforcement, or foreign affairs. Engineers have a strong advantage in the optional papers.',
        icon: '🏛️',
        isTrending: false,
        skills: ['General Studies', 'Current Affairs', 'Essay Writing', 'Optional Subject', 'Interview'],
        branches: ['ALL'],
    },
    {
        title: 'Indian Railways Engineer (JE / SSE / IRMS)',
        slug: 'indian-railways-engineer',
        category: 'Government',
        salaryRange: '₹5–9 LPA',
        demandLevel: 'High',
        examRoute: 'RRB JE / IRMS Exam',
        description: 'Work on India\'s largest railway network as a Junior Engineer or Section Engineer. Handle infrastructure, signalling, traction, and rolling stock maintenance.',
        icon: '🚄',
        isTrending: false,
        skills: ['Core Engineering', 'RRB Syllabus', 'Aptitude', 'Technical Knowledge'],
        branches: ['MECH', 'EEE', 'ECE', 'CIVIL', 'CSE'],
    },
    {
        title: 'NIC Scientist',
        slug: 'nic-scientist',
        category: 'Government',
        salaryRange: '₹8–12 LPA',
        demandLevel: 'Medium',
        examRoute: 'NIC Direct Recruitment',
        description: 'Develop and maintain government websites, portals, and digital infrastructure at the National Informatics Centre. Work on Digital India, e-governance, and cybersecurity projects.',
        icon: '🖥️',
        isTrending: false,
        skills: ['Programming', 'Networking', 'Databases', 'Cybersecurity', 'GATE CSE'],
        branches: ['CSE', 'IT'],
    },
    {
        title: 'SSC JE (Junior Engineer)',
        slug: 'ssc-je',
        category: 'Government',
        salaryRange: '₹4–7 LPA',
        demandLevel: 'High',
        examRoute: 'SSC JE Exam',
        description: 'Entry-level engineering role in central government departments like CPWD, MES, BRO, and CWC. Handle infrastructure and construction projects across India.',
        icon: '🔨',
        isTrending: false,
        skills: ['Core Engineering Basics', 'Technical Aptitude', 'SSC Syllabus'],
        branches: ['CIVIL', 'MECH', 'EEE'],
    },
    {
        title: 'SSC CGL Officer (Income Tax / CBI / Auditor)',
        slug: 'ssc-cgl-officer',
        category: 'Government',
        salaryRange: '₹6–10 LPA',
        demandLevel: 'Very High',
        examRoute: 'SSC CGL Exam',
        description: 'Join central government as Income Tax Inspector, CBI Sub-Inspector, Auditor, or Assistant Section Officer. No engineering-specific role but open to all B.Tech graduates.',
        icon: '📁',
        isTrending: false,
        skills: ['Quantitative Aptitude', 'Reasoning', 'English', 'General Awareness'],
        branches: ['ALL'],
    },
    {
        title: 'Banking PO / Specialist Officer (SBI / IBPS)',
        slug: 'banking-po',
        category: 'Government',
        salaryRange: '₹6–10 LPA',
        demandLevel: 'Very High',
        examRoute: 'IBPS PO / SBI PO / IBPS SO IT Officer',
        description: 'Join public sector banks as Probationary Officer or IT Specialist Officer. Excellent salary, promotions, and work-life balance. IBPS SO is tailor-made for CSE/IT engineers.',
        icon: '🏦',
        isTrending: false,
        skills: ['Aptitude', 'Reasoning', 'English', 'Banking Awareness', 'Computer Knowledge'],
        branches: ['ALL'],
    },
    {
        title: 'RBI Grade B Officer',
        slug: 'rbi-grade-b',
        category: 'Government',
        salaryRange: '₹18 LPA (gross)',
        demandLevel: 'Medium',
        examRoute: 'RBI Grade B Exam',
        description: 'One of the most coveted banking jobs in India. Gross salary over ₹1.5 lakh/month. Work on monetary policy, banking regulation, and economic research.',
        icon: '💰',
        isTrending: true,
        skills: ['Economics', 'Finance', 'Reasoning', 'English', 'Current Affairs', 'Quantitative Aptitude'],
        branches: ['ALL'],
    },
    {
        title: 'Defence Technical Officer (Army / Navy / Air Force)',
        slug: 'defence-technical-officer',
        category: 'Government',
        salaryRange: '₹7–12 LPA + perks',
        demandLevel: 'Medium',
        examRoute: 'AFCAT / TGC / CDS / NCC Entry',
        description: 'Serve as a commissioned officer in India\'s armed forces in a technical capacity. Manage systems, aircraft, ships, or IT infrastructure with unmatched lifestyle and pride.',
        icon: '🎗️',
        isTrending: false,
        skills: ['Engineering Domain', 'Physical Fitness', 'Leadership', 'AFCAT Syllabus'],
        branches: ['CSE', 'ECE', 'MECH', 'EEE'],
    },
    {
        title: 'State PSC / PWD Engineer',
        slug: 'state-psc-pwd-engineer',
        category: 'Government',
        salaryRange: '₹5–9 LPA',
        demandLevel: 'High',
        examRoute: 'State Public Service Commission Exams',
        description: 'Serve in state-level public works, irrigation, or electricity departments. Good work-life balance with home state posting preference. Thousands of vacancies across states.',
        icon: '🌆',
        isTrending: false,
        skills: ['Core Engineering', 'State-specific Syllabus', 'GK', 'Aptitude'],
        branches: ['CIVIL', 'MECH', 'EEE', 'ECE'],
    },
    {
        title: 'CDAC Engineer / Scientist',
        slug: 'cdac-engineer',
        category: 'Government',
        salaryRange: '₹6–10 LPA',
        demandLevel: 'Medium',
        examRoute: 'CDAC Direct Recruitment',
        description: 'Work at C-DAC on supercomputing, AI, cybersecurity, e-health, and language technology. A great mix of research and development under Government of India.',
        icon: '🖧',
        isTrending: false,
        skills: ['Programming', 'HPC', 'AI/ML', 'Cybersecurity', 'GATE'],
        branches: ['CSE', 'ECE'],
    },
    {
        title: 'Government College Lecturer / Assistant Professor',
        slug: 'government-lecturer',
        category: 'Government',
        salaryRange: '₹6–12 LPA',
        demandLevel: 'Medium',
        examRoute: 'GATE + NET / State PSC Teaching Exams',
        description: 'Teach engineering subjects at government colleges and institutions. Requires GATE and/or NET qualification. Excellent job security with pension and academic freedom.',
        icon: '📚',
        isTrending: false,
        skills: ['Subject Expertise', 'Communication', 'GATE', 'UGC NET', 'Research'],
        branches: ['CSE', 'ECE', 'MECH', 'CIVIL', 'EEE'],
    },

    // ═══════════════════════════════════════════════
    // 🎓 HIGHER STUDIES  (13 paths)
    // ═══════════════════════════════════════════════
    {
        title: 'M.Tech (IITs / NITs / IIITs)',
        slug: 'mtech-iit-nit',
        category: 'Higher Studies',
        salaryRange: '₹10–25 LPA',
        demandLevel: 'High',
        examRoute: 'GATE',
        duration: '2 years',
        description: 'Deepen technical expertise in your domain at India\'s top institutes. Strong ROI for those targeting R&D, PSU jobs, or PhD. IIT M.Tech opens doors comparable to B.Tech from IIT.',
        icon: '🏫',
        isTrending: false,
        skills: ['GATE Preparation', 'Core Engineering', 'Research Aptitude', 'Programming'],
        branches: ['CSE', 'ECE', 'MECH', 'CIVIL', 'EEE'],
    },
    {
        title: 'MBA (IIMs / XLRI / ISB)',
        slug: 'mba-iim-xlri',
        category: 'Higher Studies',
        salaryRange: '₹15–50 LPA',
        demandLevel: 'Very High',
        examRoute: 'CAT / XAT / GMAT',
        duration: '2 years',
        description: 'Transition from technical to managerial roles. Engineers with MBA have dual advantage in consulting, product management, finance, and entrepreneurship. Top B-schools offer ₹25–50 LPA packages.',
        icon: '💼',
        isTrending: true,
        skills: ['CAT Prep', 'Quantitative Aptitude', 'Logical Reasoning', 'Communication', 'Leadership'],
        branches: ['ALL'],
    },
    {
        title: 'MS Abroad (USA / Germany / Canada / Australia)',
        slug: 'ms-abroad',
        category: 'Higher Studies',
        salaryRange: '₹40–100 LPA',
        demandLevel: 'Very High',
        examRoute: 'GRE + TOEFL / IELTS',
        duration: '1.5–2 years',
        description: 'Pursue a Master of Science at top global universities. Opens doors to international careers, PR pathways, and cutting-edge research. Specializations in CS, AI, Data Science, and Robotics are most popular.',
        icon: '✈️',
        isTrending: true,
        skills: ['GRE', 'TOEFL/IELTS', 'SOP Writing', 'Research Skills', 'Programming'],
        branches: ['CSE', 'ECE', 'MECH', 'CIVIL', 'EEE'],
    },
    {
        title: 'MBA Abroad (USA / UK / Canada)',
        slug: 'mba-abroad',
        category: 'Higher Studies',
        salaryRange: '₹80–100 LPA',
        demandLevel: 'High',
        examRoute: 'GMAT + IELTS / TOEFL',
        duration: '2 years',
        description: 'Earn a global MBA from Harvard, Wharton, or INSEAD. Offers international career exposure, elite networking, and C-suite pathways. High investment but very high returns.',
        icon: '🌍',
        isTrending: false,
        skills: ['GMAT', 'IELTS/TOEFL', 'Leadership', 'Work Experience', 'Essays'],
        branches: ['ALL'],
    },
    {
        title: 'PhD in India (IITs / IISc / IIITs)',
        slug: 'phd-india',
        category: 'Higher Studies',
        salaryRange: '₹12–30 LPA (post-PhD)',
        demandLevel: 'Medium',
        examRoute: 'GATE + Institute Interview',
        duration: '4–5 years',
        description: 'Contribute original research in your field and enter academia or R&D. Fellowship of ₹31,000–37,000/month during PhD. Post-PhD roles at IITs, DRDO, or product companies.',
        icon: '🔭',
        isTrending: false,
        skills: ['GATE', 'Research Aptitude', 'Paper Writing', 'Domain Expertise'],
        branches: ['CSE', 'ECE', 'MECH', 'CIVIL', 'EEE'],
    },
    {
        title: 'PhD Abroad (USA / Germany / UK)',
        slug: 'phd-abroad',
        category: 'Higher Studies',
        salaryRange: '₹50–100 LPA (post-PhD)',
        demandLevel: 'Medium',
        examRoute: 'GRE + Research Proposal + SOP',
        duration: '4–6 years (fully funded)',
        description: 'Pursue fully funded doctoral research at MIT, Stanford, or top European universities. Monthly stipend covers living expenses. PhD abroad leads to Big Tech research roles or top-tier academia.',
        icon: '🎓',
        isTrending: false,
        skills: ['GRE', 'Research Papers', 'SOP', 'Strong Academics', 'Domain Mastery'],
        branches: ['CSE', 'ECE', 'MECH'],
    },
    {
        title: 'MBA in Business Analytics / IT',
        slug: 'mba-business-analytics',
        category: 'Higher Studies',
        salaryRange: '₹12–30 LPA',
        demandLevel: 'High',
        examRoute: 'CAT / XAT / GMAT',
        duration: '2 years',
        description: 'Blend management with data and technology skills. Best for engineers aiming for analytics, consulting, or product roles without moving away from tech completely.',
        icon: '📉',
        isTrending: true,
        skills: ['CAT/GMAT', 'Statistics', 'SQL', 'Python', 'Business Acumen'],
        branches: ['CSE', 'IT', 'ECE'],
    },
    {
        title: 'MS in Data Science / AI',
        slug: 'ms-data-science-ai',
        category: 'Higher Studies',
        salaryRange: '₹40–80 LPA',
        demandLevel: 'Very High',
        examRoute: 'GRE + TOEFL',
        duration: '1.5–2 years',
        description: 'Specialize in Artificial Intelligence, Machine Learning, or Data Science at top universities. Extremely high ROI with global job placements at FAANG and AI startups.',
        icon: '🧠',
        isTrending: true,
        skills: ['Python', 'ML Fundamentals', 'Math / Stats', 'GRE', 'TOEFL'],
        branches: ['CSE', 'IT', 'ECE'],
    },
    {
        title: 'MS in Cybersecurity',
        slug: 'ms-cybersecurity',
        category: 'Higher Studies',
        salaryRange: '₹35–80 LPA',
        demandLevel: 'High',
        examRoute: 'GRE + TOEFL',
        duration: '1.5–2 years',
        description: 'Specialize in cybersecurity, ethical hacking, and digital forensics. One of the fastest-growing fields globally with massive shortage of skilled professionals.',
        icon: '🔒',
        isTrending: true,
        skills: ['Networking', 'Linux', 'GRE', 'Cryptography', 'Security Fundamentals'],
        branches: ['CSE', 'IT', 'ECE'],
    },
    {
        title: 'MS in Computer Science',
        slug: 'ms-computer-science',
        category: 'Higher Studies',
        salaryRange: '₹40–100 LPA',
        demandLevel: 'Very High',
        examRoute: 'GRE + TOEFL',
        duration: '1.5–2 years',
        description: 'The most popular MS choice for Indian engineering graduates. Opens doors to software engineering, research, and product roles at top global tech companies.',
        icon: '🖥️',
        isTrending: true,
        skills: ['DSA', 'Programming', 'GRE', 'TOEFL', 'System Design', 'Projects'],
        branches: ['CSE', 'IT'],
    },
    {
        title: 'LLB (Law after Engineering)',
        slug: 'llb-law',
        category: 'Higher Studies',
        salaryRange: '₹5–20 LPA',
        demandLevel: 'Medium',
        examRoute: 'CLAT PG / Direct Admission',
        duration: '3 years',
        description: 'Combine engineering and law to become a technology lawyer, IP attorney, or legal consultant for tech companies. Unique and high-demand niche especially in patent law.',
        icon: '⚖️',
        isTrending: false,
        skills: ['Legal Aptitude', 'Communication', 'Tech Domain Knowledge', 'Research'],
        branches: ['ALL'],
    },
    {
        title: 'PGDM (Post Graduate Diploma in Management)',
        slug: 'pgdm',
        category: 'Higher Studies',
        salaryRange: '₹8–20 LPA',
        demandLevel: 'Medium',
        examRoute: 'CAT / MAT / XAT',
        duration: '2 years',
        description: 'Industry-focused alternative to MBA offered by autonomous institutes like SP Jain, MDI, IMT. Often more flexible and industry-connected than traditional MBA programs.',
        icon: '🏢',
        isTrending: false,
        skills: ['CAT/MAT', 'Communication', 'Leadership', 'Business Strategy'],
        branches: ['ALL'],
    },
    {
        title: 'Professional Certifications (AWS / GCP / CFA / PMP)',
        slug: 'professional-certifications',
        category: 'Higher Studies',
        salaryRange: '30–60% salary boost',
        demandLevel: 'Very High',
        examRoute: 'Vendor Certification Exams',
        duration: '3–6 months',
        description: 'Short-term certifications that significantly boost employability and salary. AWS/GCP for cloud, CFA for finance, PMP for project management, and CISSP for cybersecurity.',
        icon: '📜',
        isTrending: true,
        skills: ['Domain Specific', 'Self-Study', 'Practice Tests', 'Hands-on Projects'],
        branches: ['ALL'],
    },

    // ═══════════════════════════════════════════════
    // 🚀 ENTREPRENEURSHIP  (13 paths)
    // ═══════════════════════════════════════════════
    {
        title: 'SaaS Startup',
        slug: 'saas-startup',
        category: 'Entrepreneurship',
        salaryRange: 'Variable (₹0 to Crores)',
        demandLevel: 'High',
        capitalNeeded: 'Low–Medium (₹1–10L)',
        riskLevel: 'Medium',
        description: 'Build subscription-based software products for businesses. SaaS is the most popular model for tech entrepreneurs due to recurring revenue, low overhead, and global scalability.',
        icon: '☁️',
        isTrending: true,
        skills: ['Full Stack Dev', 'Product Thinking', 'Marketing', 'Sales', 'Customer Research'],
        branches: ['CSE', 'IT'],
    },
    {
        title: 'EdTech Startup',
        slug: 'edtech-startup',
        category: 'Entrepreneurship',
        salaryRange: 'Variable',
        demandLevel: 'High',
        capitalNeeded: 'Low (₹50K–5L)',
        riskLevel: 'Medium',
        description: 'Build learning platforms, skill-building apps, or tutoring services. India\'s education market is massive with huge demand for affordable quality education — just like Way2Fresher.',
        icon: '📖',
        isTrending: true,
        skills: ['Content Creation', 'Web Dev', 'Marketing', 'Curriculum Design', 'Community Building'],
        branches: ['ALL'],
    },
    {
        title: 'FinTech Startup',
        slug: 'fintech-startup',
        category: 'Entrepreneurship',
        salaryRange: 'Variable',
        demandLevel: 'High',
        capitalNeeded: 'Medium (₹5–50L + compliance)',
        riskLevel: 'High',
        description: 'Build payment systems, lending platforms, investment tools, or insurance tech. India\'s FinTech ecosystem is the third largest globally with massive VC investment.',
        icon: '💳',
        isTrending: true,
        skills: ['Full Stack Dev', 'Finance Knowledge', 'RBI Compliance', 'Security', 'API Integration'],
        branches: ['CSE', 'IT'],
    },
    {
        title: 'HealthTech Startup',
        slug: 'healthtech-startup',
        category: 'Entrepreneurship',
        salaryRange: 'Variable',
        demandLevel: 'High',
        capitalNeeded: 'Medium (₹5–25L)',
        riskLevel: 'Medium',
        description: 'Build telemedicine platforms, diagnostic tools, hospital management systems, or AI-based health assistants. Post-COVID, healthcare digitization has accelerated massively.',
        icon: '🏥',
        isTrending: true,
        skills: ['Healthcare Domain', 'HIPAA/Data Privacy', 'AI/ML', 'Mobile Dev', 'Partnerships'],
        branches: ['CSE', 'IT', 'ECE'],
    },
    {
        title: 'AgriTech Startup',
        slug: 'agritech-startup',
        category: 'Entrepreneurship',
        salaryRange: 'Variable',
        demandLevel: 'Medium',
        capitalNeeded: 'Low–Medium (₹1–20L)',
        riskLevel: 'Medium',
        description: 'Solve India\'s agricultural challenges with tech — from precision farming and crop monitoring to supply chain and marketplace platforms connecting farmers to buyers.',
        icon: '🌾',
        isTrending: false,
        skills: ['IoT', 'Mobile Dev', 'Supply Chain', 'Rural Market Knowledge', 'Data Analytics'],
        branches: ['CSE', 'ECE', 'MECH'],
    },
    {
        title: 'AI / ML Product Company',
        slug: 'ai-ml-product-company',
        category: 'Entrepreneurship',
        salaryRange: 'Variable',
        demandLevel: 'Very High',
        capitalNeeded: 'Low–Medium (₹1–15L)',
        riskLevel: 'Medium',
        description: 'Build AI-powered tools, automation products, or Generative AI applications. One of the hottest startup categories globally in 2024–26 with massive VC interest.',
        icon: '🤖',
        isTrending: true,
        skills: ['Python', 'ML/DL', 'Generative AI', 'Product Design', 'Cloud Deployment'],
        branches: ['CSE', 'IT', 'ECE'],
    },
    {
        title: 'E-commerce / D2C Brand',
        slug: 'ecommerce-d2c',
        category: 'Entrepreneurship',
        salaryRange: 'Variable',
        demandLevel: 'Medium',
        capitalNeeded: 'Medium (₹5–50L for inventory)',
        riskLevel: 'Medium',
        description: 'Launch a direct-to-consumer brand in niche categories like fashion, health, electronics, or food. Platforms like Shopify, Amazon, and Meesho make distribution accessible.',
        icon: '🛒',
        isTrending: false,
        skills: ['Digital Marketing', 'Inventory Management', 'Branding', 'Supply Chain', 'Shopify'],
        branches: ['ALL'],
    },
    {
        title: 'Freelance Agency (Dev / Design / Marketing)',
        slug: 'freelance-agency',
        category: 'Entrepreneurship',
        salaryRange: '₹5–50 LPA',
        demandLevel: 'High',
        capitalNeeded: 'Very Low (< ₹50K)',
        riskLevel: 'Low',
        description: 'Start a services agency offering web development, UI/UX design, or digital marketing to clients. Scale from solo freelancer to a small team. Lowest risk entrepreneurship path.',
        icon: '🏗️',
        isTrending: false,
        skills: ['Technical Skills', 'Client Management', 'Invoicing', 'Proposals', 'Networking'],
        branches: ['CSE', 'IT', 'ALL'],
    },
    {
        title: 'Content Creator / YouTuber / Blogger',
        slug: 'content-creator',
        category: 'Entrepreneurship',
        salaryRange: '₹1–50 LPA',
        demandLevel: 'Medium',
        capitalNeeded: 'Very Low (< ₹20K setup)',
        riskLevel: 'Low',
        description: 'Build an audience around tech, education, finance, or coding. Monetize via YouTube AdSense, sponsorships, courses, and affiliate marketing. Long-term but high-impact brand building.',
        icon: '🎥',
        isTrending: true,
        skills: ['Content Strategy', 'Video Editing', 'SEO', 'Communication', 'Consistency'],
        branches: ['ALL'],
    },
    {
        title: 'Deep Tech Startup (Robotics / Space / Semiconductors)',
        slug: 'deep-tech-startup',
        category: 'Entrepreneurship',
        salaryRange: 'Variable (High ceiling)',
        demandLevel: 'High',
        capitalNeeded: 'High (₹50L–Crores + VC funding)',
        riskLevel: 'High',
        description: 'Work on frontier technologies — space tech, robotics, semiconductors, or quantum computing. High risk but massive impact and valuation potential. India is emerging as a deep tech hub.',
        icon: '🔬',
        isTrending: true,
        skills: ['Domain Expertise', 'Fundraising', 'Hardware Engineering', 'Research', 'Team Building'],
        branches: ['CSE', 'ECE', 'MECH', 'EEE'],
    },
    {
        title: 'Social Impact / NGO Tech Venture',
        slug: 'social-impact-tech',
        category: 'Entrepreneurship',
        salaryRange: '₹3–15 LPA (grant-funded)',
        demandLevel: 'Medium',
        capitalNeeded: 'Low (Grant / CSR funded)',
        riskLevel: 'Low',
        description: 'Build tech solutions for rural India, accessibility, or environmental challenges. Funded by government grants, CSR funds, and impact investors. Personally fulfilling and globally recognized.',
        icon: '🌱',
        isTrending: false,
        skills: ['Social Entrepreneurship', 'Grant Writing', 'Community Engagement', 'Tech for Good'],
        branches: ['ALL'],
    },
    {
        title: 'EV / Clean Energy Startup',
        slug: 'ev-clean-energy-startup',
        category: 'Entrepreneurship',
        salaryRange: 'Variable',
        demandLevel: 'High',
        capitalNeeded: 'High (₹25L–Crores)',
        riskLevel: 'Medium',
        description: 'Build EV charging infrastructure, battery tech, solar solutions, or energy storage systems. India\'s EV market is growing at 40%+ CAGR with massive government policy support.',
        icon: '⚡',
        isTrending: true,
        skills: ['Electrical Engineering', 'Battery Tech', 'Regulatory Knowledge', 'Fundraising'],
        branches: ['EEE', 'MECH', 'ECE'],
    },
    {
        title: 'Gaming / AR / VR Startup',
        slug: 'gaming-ar-vr-startup',
        category: 'Entrepreneurship',
        salaryRange: 'Variable',
        demandLevel: 'Medium',
        capitalNeeded: 'Medium (₹5–30L)',
        riskLevel: 'High',
        description: 'Develop mobile games, AR filters, VR experiences, or gaming platforms. India\'s mobile gaming market is the 2nd largest in the world by user base and growing fast.',
        icon: '🎮',
        isTrending: false,
        skills: ['Unity', 'Unreal Engine', '3D Modelling', 'Game Design', 'Monetization'],
        branches: ['CSE', 'IT'],
    },
];

// ═══════════════════════════════════════════════════════════════
// Quiz & Course data (unchanged)
// ═══════════════════════════════════════════════════════════════

const quizQuestions = [
    // --- Step 1: Degree Selection ---
    {
        step: 1, field: 'degree',
        question: 'What is your current or acquiring degree?',
        subtitle: 'Select your field of study to customize your career quiz.',
        icon: '🎓',
        options: [
            { id: 'eng', label: '🎓 Engineering (B.Tech / B.E.)', value: 'Engineering' },
            { id: 'ca', label: '💻 Computer Applications (BCA / MCA / B.Sc CS)', value: 'ComputerApplications' },
            { id: 'mgt', label: '📊 Business & Management (BBA / MBA / BMS)', value: 'Management' },
            { id: 'com', label: '💼 Commerce & Finance (B.Com / M.Com / CA)', value: 'Commerce' },
            { id: 'sci', label: '🔬 Sciences (B.Sc / M.Sc)', value: 'Sciences' },
            { id: 'art', label: '🎨 Arts & Humanities (BA / MA)', value: 'Arts' },
        ],
    },

    // --- Engineering Track ---
    {
        step: 2, field: 'eng_branch',
        question: 'Which engineering branch are you from?',
        subtitle: 'Your branch helps us find careers that fit your background',
        icon: '⚙️',
        options: [
            { id: 'cse', label: 'Computer Science (CSE/IT)', value: 'CSE' },
            { id: 'ece', label: 'Electronics & Communication (ECE)', value: 'ECE' },
            { id: 'mech', label: 'Mechanical Engineering', value: 'MECH' },
            { id: 'civil', label: 'Civil Engineering', value: 'CIVIL' },
            { id: 'eee', label: 'Electrical & Electronics (EEE)', value: 'EEE' },
        ],
    },
    {
        step: 3, field: 'eng_interest',
        question: 'What is your primary career interest?',
        subtitle: 'Choose the domain that excites you the most',
        icon: '💡',
        options: [
            { id: 'coding', label: '💻 Software & Coding', value: 'Coding' },
            { id: 'core', label: '⚙️ Core Engineering & Design', value: 'Core' },
            { id: 'management', label: '📊 Business & Management', value: 'Management' },
            { id: 'research', label: '🔬 Research & Development', value: 'Research' },
            { id: 'civil_public', label: '🏗️ Civil & Public Works', value: 'Civil' },
        ],
    },
    {
        step: 4, field: 'eng_risk',
        question: 'How much career risk can you handle?',
        subtitle: 'Risk tolerance affects which career paths fit your profile',
        icon: '⚖️',
        options: [
            { id: 'low', label: '🛡️ Low — I prefer job security', value: 'Low' },
            { id: 'medium', label: '⚖️ Medium — Balanced risk is fine', value: 'Medium' },
            { id: 'high', label: '🎯 High — High risk for high reward', value: 'High' },
        ],
    },
    {
        step: 5, field: 'eng_work',
        question: 'What kind of work environment do you prefer?',
        subtitle: 'Select the setting you see yourself working in',
        icon: '🏢',
        options: [
            { id: 'mnc', label: '🌐 Tech MNCs / Product Companies', value: 'TechMNC' },
            { id: 'core_ind', label: '🏭 Core Industries (Manufacturing/Power)', value: 'CoreInd' },
            { id: 'govt', label: '🏛️ Government / Public Sector (PSUs)', value: 'Govt' },
            { id: 'lab', label: '🔬 Research Labs / Academia', value: 'ResearchLab' },
            { id: 'startups', label: '🚀 High-growth Tech Startups', value: 'Startups' },
        ],
    },
    {
        step: 6, field: 'eng_budget',
        question: 'What is your financial flexibility for further education?',
        subtitle: 'This helps evaluate options like MS abroad or premium MBA',
        icon: '💵',
        options: [
            { id: 'limited', label: '💳 Limited budget — Need job immediately or affordable path', value: 'Limited' },
            { id: 'afford', label: '💰 Can invest in higher studies (MS / MBA)', value: 'Afford' },
        ],
    },

    // --- Computer Applications Track ---
    {
        step: 2, field: 'ca_specialization',
        question: 'What is your primary area of focus in IT?',
        subtitle: 'Choose your desired specialization',
        icon: '🖥️',
        options: [
            { id: 'web', label: '🌐 Web & App Development', value: 'WebDev' },
            { id: 'data', label: '📊 Data Science & AI/ML', value: 'DataAI' },
            { id: 'cyber', label: '🔒 Cybersecurity & Networks', value: 'CyberNet' },
            { id: 'sys', label: '🖧 Systems Administration & Cloud', value: 'SysAdmin' },
            { id: 'pm', label: '📋 Project Management & IT Ops', value: 'Management' },
        ],
    },
    {
        step: 3, field: 'ca_coding',
        question: 'How would you rate your programming confidence?',
        subtitle: 'Be honest about your relationship with coding',
        icon: '💻',
        options: [
            { id: 'love', label: '🔥 Love coding — I code projects for fun', value: 'LoveCoding' },
            { id: 'mod', label: '👍 Moderate coding — I can code but open to non-coding tech roles', value: 'ModerateCoding' },
            { id: 'nocode', label: '🎨 Design/Management — Prefer design or no-code paths', value: 'NoCode' },
        ],
    },
    {
        step: 4, field: 'ca_risk',
        question: 'How much career risk are you comfortable with?',
        subtitle: 'This guides recommendations towards startups, MNCs, or freelancing',
        icon: '⚖️',
        options: [
            { id: 'low', label: '🛡️ Low — I prefer stable IT services firms', value: 'Low' },
            { id: 'medium', label: '⚖️ Medium — MNCs or established product companies', value: 'Medium' },
            { id: 'high', label: '🚀 High — Tech startups or remote freelancing', value: 'High' },
        ],
    },
    {
        step: 5, field: 'ca_salary',
        question: 'What is your primary career goal right now?',
        subtitle: 'Match career options to your ultimate target',
        icon: '💰',
        options: [
            { id: 'max', label: '💸 Maximize starting salary potential', value: 'MaxSalary' },
            { id: 'life', label: '🧘 Work-life balance and stable hours', value: 'WorkLife' },
            { id: 'learn', label: '📈 Learning opportunities & rapid promotion', value: 'Learning' },
        ],
    },
    {
        step: 6, field: 'ca_study',
        question: 'Are you planning to pursue further studies?',
        subtitle: 'Some roles benefit from MCA, MS, or professional certifications',
        icon: '📚',
        options: [
            { id: 'no', label: '❌ No — I want to start working immediately', value: 'No' },
            { id: 'yes', label: '✅ Yes — Open to PG degrees or specialized certifications', value: 'Yes' },
        ],
    },

    // --- Business & Management Track ---
    {
        step: 2, field: 'mgt_specialization',
        question: 'Which business domain interests you most?',
        subtitle: 'Select the field that matches your interest',
        icon: '📊',
        options: [
            { id: 'mkt', label: '📣 Marketing & Brand Management', value: 'Marketing' },
            { id: 'fin', label: '💵 Finance, Banking & Consulting', value: 'Finance' },
            { id: 'hr', label: '👥 Human Resource Management', value: 'HR' },
            { id: 'ops', label: '📦 Operations & Logistics', value: 'Operations' },
            { id: 'strat', label: '💡 Corporate Strategy & Business Development', value: 'Strategy' },
        ],
    },
    {
        step: 3, field: 'mgt_strength',
        question: 'What is your main professional strength?',
        subtitle: 'Your strongest skill determines your suitability for roles',
        icon: '🤝',
        options: [
            { id: 'lead', label: '👑 Leadership & Team Management', value: 'Leadership' },
            { id: 'data', label: '📈 Data Analysis & Strategic Planning', value: 'DataStrategy' },
            { id: 'comm', label: '💬 Communication & Public Relations', value: 'Communication' },
            { id: 'solve', label: '⚙️ Problem Solving & Operations management', value: 'ProblemSolving' },
        ],
    },
    {
        step: 4, field: 'mgt_risk',
        question: 'How much performance/target risk can you handle?',
        subtitle: 'Management careers range from stable HR roles to high-target sales roles',
        icon: '⚖️',
        options: [
            { id: 'low', label: '🛡️ Low — Prefer stable fixed salary and hours', value: 'Low' },
            { id: 'medium', label: '⚖️ Medium — Base salary plus performance bonuses', value: 'Medium' },
            { id: 'high', label: '🎯 High — High commission / target-heavy executive tracks', value: 'High' },
        ],
    },
    {
        step: 5, field: 'mgt_company',
        question: 'What type of organization do you aim to join?',
        subtitle: 'Select your preferred professional home',
        icon: '🏢',
        options: [
            { id: 'corp', label: '🌐 Large Corporate MNCs', value: 'CorporateMNC' },
            { id: 'consult', label: '💼 Management Consultancies', value: 'Consultancy' },
            { id: 'startup', label: '🚀 Fast-paced Startups or Venture Capital', value: 'StartupsVC' },
            { id: 'govt', label: '🏛️ Government / Public Administration', value: 'Government' },
        ],
    },
    {
        step: 6, field: 'mgt_budget',
        question: 'Do you plan to pursue a premium MBA program (e.g. IIMs or abroad)?',
        subtitle: 'Premium MBA programs open elite consulting and PM career options',
        icon: '💵',
        options: [
            { id: 'yes', label: '✅ Yes — Prepared to invest in a top-tier management degree', value: 'Yes' },
            { id: 'no', label: '❌ No — Prefer direct entry or company executive training', value: 'No' },
        ],
    },

    // --- Commerce & Finance Track ---
    {
        step: 2, field: 'com_specialization',
        question: 'Which area of commerce/finance interests you the most?',
        subtitle: 'Select your primary interest',
        icon: '💵',
        options: [
            { id: 'act', label: '📊 Accounting & Auditing', value: 'Accounting' },
            { id: 'corp', label: '💼 Corporate Finance & Investment Banking', value: 'CorpFinance' },
            { id: 'bank', label: '🏦 Commercial Banking & Insurance', value: 'Banking' },
            { id: 'tax', label: '📜 Taxation & Corporate Law', value: 'Taxation' },
            { id: 'mkt', label: '📈 Stock Markets & Trading', value: 'Markets' },
        ],
    },
    {
        step: 3, field: 'com_professional',
        question: 'Are you planning to prepare for professional certification exams?',
        subtitle: 'Exams like CA, CFA, CS, or CMA define specialized finance careers',
        icon: '📝',
        options: [
            { id: 'yes', label: '✅ Yes — Aiming for CA / CFA / CS certifications', value: 'Yes' },
            { id: 'no', label: '❌ No — Prefer standard corporate jobs after graduation', value: 'No' },
        ],
    },
    {
        step: 4, field: 'com_risk',
        question: 'What is your preferred career pace?',
        subtitle: 'Select between corporate stability and market volatility',
        icon: '⚖️',
        options: [
            { id: 'stable', label: '🛡️ Stable — Steady growth, compliance, and auditing', value: 'Stable' },
            { id: 'dynamic', label: '⚡ Dynamic — High pressure, fast growth, investment or trading', value: 'Dynamic' },
        ],
    },
    {
        step: 5, field: 'com_company',
        question: 'Which industry segment do you target?',
        subtitle: 'Select your target work domain',
        icon: '🏢',
        options: [
            { id: 'big4', label: '💼 Big 4 Accounting & Consulting Firms', value: 'Big4' },
            { id: 'ib', label: '📈 Investment Banks / Asset Management', value: 'InvestmentBanks' },
            { id: 'pub', label: '🏦 Public Sector or Commercial Banks', value: 'PublicBanks' },
            { id: 'fin', label: '🏢 Corporate Finance Departments', value: 'CorporateFin' },
        ],
    },
    {
        step: 6, field: 'com_study',
        question: 'Are you open to higher education like M.Com or MBA Finance?',
        subtitle: 'Post-graduate qualifications can accelerate corporate finance careers',
        icon: '📚',
        options: [
            { id: 'yes', label: '✅ Yes — Plan to pursue PG / MBA', value: 'Yes' },
            { id: 'no', label: '❌ No — Prefer to start working immediately', value: 'No' },
        ],
    },

    // --- Sciences Track ---
    {
        step: 2, field: 'sci_domain',
        question: 'Which science field are you pursuing?',
        subtitle: 'Specify your core science discipline',
        icon: '🔬',
        options: [
            { id: 'pcm', label: '📐 Physics, Chemistry, or Mathematics', value: 'PCM' },
            { id: 'bio', label: '🧬 Biotechnology, Biology, or Life Sciences', value: 'BioTech' },
            { id: 'comp', label: '💻 Computer Science or Data Science', value: 'CompSci' },
            { id: 'env', label: '🌱 Environmental Science & Ecology', value: 'Environmental' },
        ],
    },
    {
        step: 3, field: 'sci_interest',
        question: 'What is your ultimate career interest in Science?',
        subtitle: 'Select your preferred professional direction',
        icon: '💡',
        options: [
            { id: 'research', label: '🏫 Academic Research & University Teaching', value: 'ResearchTeaching' },
            { id: 'rd', label: '🧬 R&D in Private Sector (Pharma, Biotech, Tech)', value: 'PrivateRD' },
            { id: 'labs', label: '🏛️ Government Scientific Labs (ISRO, DRDO, CSIR)', value: 'GovtLabs' },
            { id: 'tech', label: '📊 Applied Analytics & Tech Roles', value: 'AppliedAnalytics' },
        ],
    },
    {
        step: 4, field: 'sci_study',
        question: 'Are you open to long-term post-graduate studies?',
        subtitle: 'Research careers in science usually require M.Sc or PhD',
        icon: '📚',
        options: [
            { id: 'yes', label: '✅ Yes — Ready to invest in M.Sc and PhD', value: 'Yes' },
            { id: 'no', label: '❌ No — Prefer immediate technical or analyst jobs', value: 'No' },
        ],
    },
    {
        step: 5, field: 'sci_work',
        question: 'What is your ideal work environment?',
        subtitle: 'Where do you see yourself executing your tasks?',
        icon: '🏫',
        options: [
            { id: 'lab', label: '🧪 Laboratory research and analysis', value: 'Lab' },
            { id: 'class', label: '🏫 Classroom lecturing and mentoring', value: 'Classroom' },
            { id: 'office', label: '🏢 Corporate office or tech desk', value: 'Office' },
            { id: 'field', label: '🌳 Field work, surveying, and conservation', value: 'Field' },
        ],
    },
    {
        step: 6, field: 'sci_budget',
        question: 'Do you have financial support for international MS/PhD programs?',
        subtitle: 'This helps evaluate global research vs. domestic options',
        icon: '💵',
        options: [
            { id: 'yes', label: '💰 Yes — Can fund abroad or looking for fully-funded PhDs', value: 'Yes' },
            { id: 'no', label: '💳 No — Seek affordable PG or immediate local job', value: 'No' },
        ],
    },

    // --- Arts & Humanities Track ---
    {
        step: 2, field: 'art_domain',
        question: 'What is your main field of study in Arts?',
        subtitle: 'Specify your core humanities field',
        icon: '🎨',
        options: [
            { id: 'lit', label: '📚 Literature & Linguistics', value: 'Literature' },
            { id: 'psych', label: '🧠 Psychology & Sociology', value: 'Psychology' },
            { id: 'econ', label: '📈 Economics & Political Science', value: 'Economics' },
            { id: 'art', label: '🎨 Fine Arts, Media & Creative Design', value: 'FineArts' },
            { id: 'hist', label: '🏛️ History, Geography & Archeology', value: 'History' },
        ],
    },
    {
        step: 3, field: 'art_interest',
        question: 'What kind of work excites you most?',
        subtitle: 'Select the category that matches your spark',
        icon: '💡',
        options: [
            { id: 'write', label: '✍️ Writing, Editing & Content Creation', value: 'Writing' },
            { id: 'civil', label: '🏛️ Civil Services & Public Administration', value: 'CivilServices' },
            { id: 'social', label: '👥 Counseling, Teaching & Social Work', value: 'Counseling' },
            { id: 'design', label: '🎨 Creative Design, UI/UX & Advertising', value: 'CreativeDesign' },
            { id: 'acad', label: '🔬 Research, History & Academia', value: 'Academia' },
        ],
    },
    {
        step: 4, field: 'art_risk',
        question: 'What is your approach to career stability?',
        subtitle: 'Choose between corporate, government, or freelance paths',
        icon: '⚖️',
        options: [
            { id: 'stable', label: '🏛️ Stable — Government, NGO, or institutional jobs', value: 'Stable' },
            { id: 'corp', label: '🏢 Corporate — Corporate marketing, media, or consulting', value: 'Corporate' },
            { id: 'creative', label: '🚀 Creative — Freelancing, startup, or creative agency', value: 'Creative' },
        ],
    },
    {
        step: 5, field: 'art_work',
        question: 'What is your ideal work rhythm?',
        subtitle: 'Choose the structure that matches your style',
        icon: '🧘',
        options: [
            { id: 'struct', label: '📅 Structured — Clear hours, low volatility', value: 'Structured' },
            { id: 'flex', label: '🎨 Flexible — Creative freedom, variable hours', value: 'Flexible' },
            { id: 'dyn', label: '⚡ Dynamic — Demanding hours, high impact', value: 'Dynamic' },
        ],
    },
    {
        step: 6, field: 'art_study',
        question: 'Are you planning to prepare for major competitive exams (like UPSC)?',
        subtitle: 'Civil services and bank exams are popular options for arts graduates',
        icon: '📝',
        options: [
            { id: 'yes', label: '✅ Yes — Focused on UPSC Civil Services / State exams', value: 'Yes' },
            { id: 'no', label: '❌ No — Aiming for corporate, creative, or academic career routes', value: 'No' },
        ],
    },
    // --- Engineering extra questions (7-10) ---
    {
        step: 7, field: 'eng_coding',
        question: 'How confident are you with programming?',
        subtitle: 'Be honest — this affects technical vs non-technical career recommendations',
        icon: '💻',
        options: [
            { id: 'high', label: '🔥 High — I build projects independently', value: 'High' },
            { id: 'mod', label: '👍 Moderate — I can code but prefer a mix of technical & managerial work', value: 'Moderate' },
            { id: 'low', label: '🔧 Low — I prefer hardware, design, or management roles', value: 'Low' },
        ],
    },
    {
        step: 8, field: 'eng_exam',
        question: 'Are you preparing (or planning to prepare) for any competitive exam?',
        subtitle: 'Knowing your exam plans helps narrow down the right path',
        icon: '📝',
        options: [
            { id: 'gate', label: '📐 GATE — For M.Tech or PSU jobs', value: 'GATE' },
            { id: 'gre', label: '🌍 GRE / GMAT — For MS or MBA abroad', value: 'GRE' },
            { id: 'cat', label: '📊 CAT / XAT — For MBA in India', value: 'CAT' },
            { id: 'sscje', label: '🏛️ SSC JE / CDS — For government technical jobs', value: 'SSCJE' },
            { id: 'none', label: '❌ No plans — Looking for direct job placement', value: 'NoExam' },
        ],
    },
    {
        step: 9, field: 'eng_experience',
        question: 'What is your practical experience level?',
        subtitle: 'Your internships and projects influence recruiter readiness',
        icon: '🏆',
        options: [
            { id: 'strong', label: '💪 Strong — Multiple internships and active personal projects', value: 'Strong' },
            { id: 'moderate', label: '👌 Moderate — One internship or a few projects', value: 'Moderate' },
            { id: 'limited', label: '📚 Limited — Mostly academic coursework', value: 'Limited' },
        ],
    },
    {
        step: 10, field: 'eng_location',
        question: 'What is your preferred work location?',
        subtitle: 'Location preferences affect which companies and roles suit you best',
        icon: '📍',
        options: [
            { id: 'metro', label: '🏙️ Major metros (Bangalore, Hyderabad, Pune, Delhi)', value: 'Metro' },
            { id: 'tier2', label: '🏠 Tier 2 cities or home state', value: 'Tier2' },
            { id: 'abroad', label: '✈️ Open to relocating abroad', value: 'Abroad' },
            { id: 'remote', label: '🏡 Remote / Work from home', value: 'Remote' },
        ],
    },

    // --- Computer Applications extra questions (7-10) ---
    {
        step: 7, field: 'ca_tools',
        question: 'Which technology domain are you most comfortable with?',
        subtitle: 'Your strongest tech area defines your career entry point',
        icon: '🛠️',
        options: [
            { id: 'frontend', label: '🌐 Frontend (React, Vue, HTML/CSS)', value: 'Frontend' },
            { id: 'backend', label: '🔧 Backend (Node.js, Python, Java, Databases)', value: 'Backend' },
            { id: 'aiml', label: '🤖 AI/ML (TensorFlow, scikit-learn, LLMs)', value: 'AIML' },
            { id: 'mobile', label: '📱 Mobile (Android, Flutter, React Native)', value: 'Mobile' },
            { id: 'cloud', label: '☁️ Cloud & DevOps (AWS, Docker, Linux)', value: 'Cloud' },
        ],
    },
    {
        step: 8, field: 'ca_project',
        question: 'Do you have personal projects or a public portfolio?',
        subtitle: 'Portfolio strength directly impacts your job and freelance opportunities',
        icon: '📂',
        options: [
            { id: 'active', label: '✅ Yes — Active GitHub / portfolio site with real projects', value: 'Active' },
            { id: 'inprogress', label: '🔄 In Progress — Currently building projects', value: 'InProgress' },
            { id: 'none', label: '❌ No — But planning to start soon', value: 'None' },
        ],
    },
    {
        step: 9, field: 'ca_work_env',
        question: 'What work environment suits you best?',
        subtitle: 'Matching your environment preference avoids early burnout',
        icon: '🏢',
        options: [
            { id: 'corp', label: '🏢 Structured corporate office with fixed hours', value: 'Corporate' },
            { id: 'startup', label: '🚀 Agile startup with flexible roles & hours', value: 'Startup' },
            { id: 'remote', label: '🏡 Remote-first freelancing', value: 'Remote' },
            { id: 'acad', label: '🎓 Academic or research environment', value: 'Academic' },
        ],
    },
    {
        step: 10, field: 'ca_goal',
        question: 'What is your primary 5-year career goal?',
        subtitle: 'Your long-term vision shapes which path to start on today',
        icon: '🎯',
        options: [
            { id: 'swe', label: '💻 Senior Software Engineer at a top MNC/product company', value: 'SeniorSWE' },
            { id: 'data', label: '📊 Data Scientist or AI/ML Expert', value: 'DataExpert' },
            { id: 'founder', label: '🚀 Startup Founder or Freelance Agency owner', value: 'Founder' },
            { id: 'research', label: '🔬 Research Scientist — MS/PhD track', value: 'Research' },
        ],
    },

    // --- Management & Business extra questions (7-10) ---
    {
        step: 7, field: 'mgt_experience',
        question: 'What is your current experience level?',
        subtitle: 'Work and internship experience determines which management paths are accessible now',
        icon: '💼',
        options: [
            { id: 'exp', label: '🏆 Experienced — 1+ years of work/internship experience', value: 'Experienced' },
            { id: 'some', label: '👌 Some — 1-2 internships completed', value: 'SomeExp' },
            { id: 'fresher', label: '🎓 Fresher — No experience yet', value: 'Fresher' },
        ],
    },
    {
        step: 8, field: 'mgt_industry',
        question: 'Which industry domain interests you most?',
        subtitle: 'Your target industry shapes your MBA specialization and career trajectory',
        icon: '🏭',
        options: [
            { id: 'fin', label: '💵 Financial Services, Banking & Insurance', value: 'Finance' },
            { id: 'tech', label: '💻 Technology, E-commerce & Digital', value: 'Tech' },
            { id: 'fmcg', label: '🛒 FMCG, Retail & Consumer Goods', value: 'FMCG' },
            { id: 'health', label: '🏥 Healthcare & Pharmaceuticals', value: 'Healthcare' },
            { id: 'mfg', label: '⚙️ Manufacturing, Logistics & Operations', value: 'Manufacturing' },
        ],
    },
    {
        step: 9, field: 'mgt_leadership',
        question: 'How would you describe your leadership style?',
        subtitle: 'Your management style determines which roles and cultures suit you',
        icon: '👑',
        options: [
            { id: 'collab', label: '🤝 Collaborative — I build consensus and bring people together', value: 'Collaborative' },
            { id: 'dir', label: '🎯 Directive — I lead from the front with clear decisions', value: 'Directive' },
            { id: 'anal', label: '📊 Analytical — I base decisions on data and logic', value: 'Analytical' },
            { id: 'insp', label: '💡 Inspirational — I lead with vision and motivation', value: 'Inspirational' },
        ],
    },
    {
        step: 10, field: 'mgt_goal',
        question: 'What is your 5-year career goal?',
        subtitle: 'Knowing your end goal helps us suggest the fastest path to get there',
        icon: '🎯',
        options: [
            { id: 'vp', label: '🏢 VP / Director at a large corporate MNC', value: 'VP' },
            { id: 'ceo', label: '🚀 Startup CEO or Co-Founder', value: 'CEO' },
            { id: 'policy', label: '🏛️ Policy Advisor or Government Officer (RBI, IAS)', value: 'PolicyAdvisor' },
            { id: 'finadv', label: '💰 Investment Banker or Senior Finance Analyst', value: 'FinanceAnalyst' },
        ],
    },

    // --- Commerce & Finance extra questions (7-10) ---
    {
        step: 7, field: 'com_skill',
        question: 'Which skill area are you strongest in?',
        subtitle: 'Your core competency determines your niche in finance',
        icon: '🧮',
        options: [
            { id: 'account', label: '📋 Numerical Analysis & Accounting', value: 'Accounting' },
            { id: 'val', label: '📈 Financial Modeling & Valuation', value: 'Valuation' },
            { id: 'comm', label: '💬 Communication & Client Relations', value: 'Communication' },
            { id: 'legal', label: '⚖️ Legal & Compliance Knowledge', value: 'Legal' },
        ],
    },
    {
        step: 8, field: 'com_tech',
        question: 'How comfortable are you with financial technology tools?',
        subtitle: 'Tech comfort influences whether analytics or advisory roles suit you',
        icon: '💻',
        options: [
            { id: 'high', label: '💪 High — Excel, Tally, SAP, Bloomberg, SQL', value: 'HighTech' },
            { id: 'mod', label: '👍 Moderate — Excel & basic accounting tools', value: 'ModerateTech' },
            { id: 'low', label: '📝 Low — Prefer non-technical client-facing or compliance roles', value: 'LowTech' },
        ],
    },
    {
        step: 9, field: 'com_priority',
        question: 'What is your top career priority?',
        subtitle: 'Your priority helps match you to the right finance career segment',
        icon: '🏆',
        options: [
            { id: 'sec', label: '🛡️ Job security and stable income', value: 'Security' },
            { id: 'grow', label: '📈 High earning potential and rapid growth', value: 'Growth' },
            { id: 'prest', label: '🎖️ Prestigious designations and institutional status', value: 'Prestige' },
            { id: 'bal', label: '🧘 Work-life balance and schedule flexibility', value: 'Balance' },
        ],
    },
    {
        step: 10, field: 'com_goal',
        question: 'What is your 5-year career goal?',
        subtitle: 'Your target role shapes the certifications and path you should follow today',
        icon: '🎯',
        options: [
            { id: 'cacfa', label: '📜 Chartered Accountant (CA) or CFA charterholder', value: 'CAorCFA' },
            { id: 'bank', label: '🏦 Branch Manager or Senior Banking Officer', value: 'BankManager' },
            { id: 'cfo', label: '💼 CFO or Finance Director at a company', value: 'CFO' },
            { id: 'entpre', label: '🚀 FinTech Entrepreneur or Investment Startup Founder', value: 'Entrepreneur' },
        ],
    },

    // --- Sciences extra questions (7-10) ---
    {
        step: 7, field: 'sci_skill',
        question: 'What is your strongest academic skill?',
        subtitle: 'Your core academic strength guides your career niche in science',
        icon: '🧬',
        options: [
            { id: 'math', label: '📐 Mathematical Modeling & Statistics', value: 'Math' },
            { id: 'lab', label: '🧪 Laboratory Techniques & Experimentation', value: 'Lab' },
            { id: 'prog', label: '💻 Programming & Data Analysis', value: 'Programming' },
            { id: 'write', label: '✍️ Scientific Writing & Research Review', value: 'Writing' },
        ],
    },
    {
        step: 8, field: 'sci_collab',
        question: 'Do you prefer working independently or in a team?',
        subtitle: 'Research environments vary from solitary deep work to large structured labs',
        icon: '🤝',
        options: [
            { id: 'indep', label: '🧘 Independently — Deep focused solo research', value: 'Independent' },
            { id: 'small', label: '👥 Small team — Collaborative research group', value: 'SmallTeam' },
            { id: 'large', label: '🏛️ Large organization — Structured government or industry lab', value: 'LargeOrg' },
        ],
    },
    {
        step: 9, field: 'sci_publication',
        question: 'Are you interested in academic publishing and research papers?',
        subtitle: 'Research publication interest determines academic vs. industry career paths',
        icon: '📚',
        options: [
            { id: 'very', label: '✅ Very interested — Publishing is a key career goal', value: 'VeryInterested' },
            { id: 'some', label: '🤔 Somewhat — Open to it but not my main focus', value: 'Somewhat' },
            { id: 'not', label: '❌ Not interested — Prefer applied or industry work', value: 'NotInterested' },
        ],
    },
    {
        step: 10, field: 'sci_goal',
        question: 'What is your long-term professional goal?',
        subtitle: 'Your 5-year goal determines the research or application path to pursue',
        icon: '🎯',
        options: [
            { id: 'prof', label: '🏫 Professor or Government College Lecturer', value: 'Professor' },
            { id: 'govt', label: '🚀 Scientist at ISRO / DRDO / CSIR national lab', value: 'GovtScientist' },
            { id: 'ind', label: '🏭 Researcher at a Pharma or Tech company', value: 'IndustryResearch' },
            { id: 'data', label: '📊 Data Analyst or ML Engineer in industry', value: 'DataAnalyst' },
        ],
    },

    // --- Arts & Humanities extra questions (7-10) ---
    {
        step: 7, field: 'art_skill',
        question: 'What is your strongest creative or academic skill?',
        subtitle: 'Your core skill is the foundation of your arts career path',
        icon: '✨',
        options: [
            { id: 'write', label: '✍️ Writing, Editing & Content Creation', value: 'Writing' },
            { id: 'design', label: '🎨 Visual Design & Digital Art', value: 'Design' },
            { id: 'research', label: '🔬 Research, Analysis & Critical Thinking', value: 'Research' },
            { id: 'speak', label: '🎤 Public Speaking & Debate', value: 'Speaking' },
            { id: 'counsel', label: '💚 Counseling, Empathy & Social Work', value: 'Counseling' },
        ],
    },
    {
        step: 8, field: 'art_digital',
        question: 'How comfortable are you with digital tools?',
        subtitle: 'Digital fluency is increasingly important in arts and creative careers',
        icon: '💻',
        options: [
            { id: 'high', label: '🖥️ High — I use Figma, Canva, Adobe, or video editing tools', value: 'HighDigital' },
            { id: 'mod', label: '📱 Moderate — Basic office, social media & presentation tools', value: 'ModerateDigital' },
            { id: 'low', label: '📝 Low — Prefer offline, traditional, or academic work', value: 'LowDigital' },
        ],
    },
    {
        step: 9, field: 'art_network',
        question: 'What type of professional community do you want to build?',
        subtitle: 'Your network type shapes the opportunities that come your way',
        icon: '🌐',
        options: [
            { id: 'govt', label: '🏛️ Government officials, IAS officers & policy makers', value: 'GovtNetwork' },
            { id: 'creative', label: '🎨 Creative industry — artists, designers, content creators', value: 'CreativeNetwork' },
            { id: 'corp', label: '💼 Corporate marketing, media & advertising professionals', value: 'CorporateNetwork' },
            { id: 'ngo', label: '🌱 NGO workers, activists & social entrepreneurs', value: 'NGONetwork' },
        ],
    },
    {
        step: 10, field: 'art_goal',
        question: 'What is your 5-year career goal?',
        subtitle: 'Knowing your end goal helps us map the best starting path for you today',
        icon: '🎯',
        options: [
            { id: 'civil', label: '🏛️ IAS / IPS Officer or Diplomat', value: 'CivilServant' },
            { id: 'creator', label: '🎥 Content Creator, YouTuber, or Published Author', value: 'Creator' },
            { id: 'therapist', label: '💚 Counselor, Therapist or Social Impact Entrepreneur', value: 'Therapist' },
            { id: 'design', label: '🎨 UI/UX Lead or Creative Director at a tech company', value: 'DesignLead' },
            { id: 'acad', label: '📚 Academician, Researcher or Lecturer', value: 'Academician' },
        ],
    },
];

const courseData = [
    {
        title: 'Complete Web Development Bootcamp 2026',
        description: 'Master web development from scratch with HTML, CSS, JS, Node and React.',
        price: 499,
        affiliateLink: 'https://example.com/course1',
        category: 'Web Development',
        platform: 'Udemy',
        rating: 4.8,
        totalStudents: 154200,
        isFeatured: true,
        isActive: true
    },
    {
        title: 'Machine Learning A-Z: AI, Python & R',
        description: 'Learn to create Machine Learning Algorithms in Python and R from two Data Science experts.',
        price: 599,
        affiliateLink: 'https://example.com/course2',
        category: 'AI/ML',
        platform: 'Udemy',
        rating: 4.6,
        totalStudents: 85000,
        isFeatured: true,
        isActive: true
    },
    {
        title: 'AWS Certified Solutions Architect',
        description: 'Pass the AWS Certified Solutions Architect Associate Certification exam.',
        price: 699,
        affiliateLink: 'https://example.com/course3',
        category: 'Cloud',
        platform: 'Coursera',
        rating: 4.7,
        totalStudents: 56000,
        isFeatured: false,
        isActive: true
    },
    {
        title: 'Mastering System Design',
        description: 'Prepare for technical interviews with advanced system design principles.',
        price: 399,
        affiliateLink: 'https://example.com/course4',
        category: 'SDE',
        platform: 'Educative',
        rating: 4.9,
        totalStudents: 32000,
        isFeatured: false,
        isActive: true
    }
];

async function seedDatabase(forceReseed = false) {
    try {
        const careerCount = await Career.count();
        if (careerCount === 0 || forceReseed) {
            if (forceReseed && careerCount > 0) {
                await Career.destroy({ where: {}, truncate: true, cascade: true });
                console.log('🗑️ Cleared existing career data for re-seed');
            }
            await Career.bulkCreate(careerData, { ignoreDuplicates: true });
            console.log(`✅ Seeded ${careerData.length} careers`);
        } else {
            console.log(`ℹ️ Database already has ${careerCount} careers — skipping seed`);
        }

        // Helper to strip emojis and symbols from text
        const stripEmojisAndSymbols = (text) => {
            if (typeof text !== 'string') return text;
            let clean = text.replace(/[\p{Emoji_Presentation}\p{Extended_Pictographic}]/gu, '');
            clean = clean.replace(/[\u2600-\u27BF\u2300-\u23FF\u2B00-\u2BFF\u2190-\u21FF]/g, '');
            clean = clean.replace(/[✓✕✔✖]/g, '');
            return clean.replace(/\s+/g, ' ').trim();
        };

        const cleanQuizQuestions = quizQuestions.map(q => ({
            ...q,
            icon: '', // Remove icons completely
            question: stripEmojisAndSymbols(q.question),
            subtitle: stripEmojisAndSymbols(q.subtitle),
            options: q.options?.map(opt => ({
                ...opt,
                label: stripEmojisAndSymbols(opt.label)
            }))
        }));

        // Re-seed quiz questions automatically to keep dynamic branched questions up-to-date
        await QuizQuestion.destroy({ where: {} });
        await QuizQuestion.bulkCreate(cleanQuizQuestions);
        console.log(`✅ Seeded ${cleanQuizQuestions.length} quiz questions (emojis & symbols removed)`);

        const courseCount = await Course.count();
        if (courseCount === 0 || forceReseed) {
            if (forceReseed && courseCount > 0) {
                await Course.destroy({ where: {} });
            }
            await Course.bulkCreate(courseData);
            console.log(`✅ Seeded ${courseData.length} courses`);
        } else {
            console.log(`ℹ️ Database already has ${courseCount} courses — skipping seed`);
        }

        // Seed Colleges & default chat rooms
        const collegeCount = await College.count();
        if (collegeCount === 0) {
            const initialColleges = [
                { name: 'ACE Engineering College', slug: 'aceec', domain: 'aceec.ac.in' },
                { name: 'IIT Hyderabad', slug: 'iith', domain: 'iith.ac.in' },
                { name: 'BITS Pilani', slug: 'bits-pilani', domain: 'bits-pilani.ac.in' },
                { name: 'JNTU Hyderabad', slug: 'jntuh', domain: 'jntuh.ac.in' },
                { name: 'VNR VJIET', slug: 'vnrvjiet', domain: 'vnrvjiet.ac.in' }
            ];

            const standardRooms = [
                { name: '💬 General Chat', type: 'general' },
                { name: '💼 Placement Updates', type: 'placements' },
                { name: '🎒 Internship Leads', type: 'internships' },
                { name: '🎓 Higher Studies', type: 'higher-studies' },
                { name: '🏛️ Govt Jobs Prep', type: 'government' },
                { name: '🚀 Startup Discussion', type: 'startup' }
            ];

            for (const colData of initialColleges) {
                const college = await College.create(colData);
                for (const room of standardRooms) {
                    await ChatRoom.create({
                        collegeId: college.id,
                        name: room.name,
                        type: room.type
                    });
                }
            }
            console.log(`✅ Seeded ${initialColleges.length} colleges and their chat channels`);
        } else {
            console.log(`ℹ️ Database already has ${collegeCount} colleges — skipping seed`);
        }

    } catch (err) {
        console.error('❌ Seeding error:', err.message);
    }
}

module.exports = { seedDatabase, careerData, quizQuestions, courseData };
